/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Control;
import backend.Pregunta;
import javax.swing.*;

public class Evaluacion extends JFrame {

    public Evaluacion() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRespuestas = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        panelPregunta = new javax.swing.JPanel();
        AreaPregunta = new javax.swing.JTextArea();
        rdBtnOpcion1 = new javax.swing.JRadioButton();
        rdBtnOpcion2 = new javax.swing.JRadioButton();
        rdBtnOpcion3 = new javax.swing.JRadioButton();
        rdBtnOpcion4 = new javax.swing.JRadioButton();
        panelInfo = new javax.swing.JPanel();
        lblTituloInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(204, 204, 236));
        Fondo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EVALUADOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Helvetica Neue", 1, 64))); // NOI18N

        btnAnterior.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnAnterior.setText("Pregunta Anterior");
        btnAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIniciar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSiguiente.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnSiguiente.setText("Pregunta Siguiente");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelPregunta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AreaPregunta.setEditable(false);
        AreaPregunta.setColumns(20);
        AreaPregunta.setRows(5);
        AreaPregunta.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(150, 150, 150)));

        grupoRespuestas.add(rdBtnOpcion1);
        rdBtnOpcion1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rdBtnOpcion1.setText("Opción 1");
        rdBtnOpcion1.setEnabled(false);

        grupoRespuestas.add(rdBtnOpcion2);
        rdBtnOpcion2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rdBtnOpcion2.setText("Opción 2");
        rdBtnOpcion2.setEnabled(false);

        grupoRespuestas.add(rdBtnOpcion3);
        rdBtnOpcion3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rdBtnOpcion3.setText("Opción 3");
        rdBtnOpcion3.setEnabled(false);

        grupoRespuestas.add(rdBtnOpcion4);
        rdBtnOpcion4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rdBtnOpcion4.setText("Opción 4");
        rdBtnOpcion4.setEnabled(false);

        javax.swing.GroupLayout panelPreguntaLayout = new javax.swing.GroupLayout(panelPregunta);
        panelPregunta.setLayout(panelPreguntaLayout);
        panelPreguntaLayout.setHorizontalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addGroup(panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPreguntaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdBtnOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdBtnOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPreguntaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(AreaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        panelPreguntaLayout.setVerticalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AreaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdBtnOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdBtnOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTituloInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lblTituloInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInfo.setText("EXAMEN");

        txtInfo.setEditable(false);
        txtInfo.setBackground(new java.awt.Color(255, 255, 255));
        txtInfo.setColumns(1);
        txtInfo.setLineWrap(true);
        txtInfo.setRows(12);
        txtInfo.setTabSize(16);
        txtInfo.setToolTipText("");
        jScrollPane1.setViewportView(txtInfo);

        btnReiniciar.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnReiniciar.setText("REINICIAR");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReiniciar.setEnabled(false);

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblTituloInfo))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTituloInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(712, 712, 712))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(500, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1269, 904);
    }// </editor-fold>//GEN-END:initComponents
    public void setPregunta(Pregunta p) {
        AreaPregunta.setText(p.getEnunciado());
        rdBtnOpcion1.setText(p.getRespuestas(1));
        rdBtnOpcion2.setText(p.getRespuestas(2));
        rdBtnOpcion3.setText(p.getRespuestas(3));
        rdBtnOpcion4.setText(p.getRespuestas(4));
    }
    
    private Control controlador;
    
    public void setControlador(Control controlador) {
        this.controlador = controlador;
    }
    
    public void mostrarMensaje(String mensaje) {
        txtInfo.setText(mensaje);
    }
        /* Create and display the form */
    public void limpiarSeleccion() {
        grupoRespuestas.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        // Muestra la ventana
        javax.swing.SwingUtilities.invokeLater(() -> {
            Evaluacion vista = new Evaluacion();
            vista.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea AreaPregunta;
    private javax.swing.JPanel Fondo;
    public javax.swing.JButton btnAnterior;
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnReiniciar;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.ButtonGroup grupoRespuestas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloInfo;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPregunta;
    public javax.swing.JRadioButton rdBtnOpcion1;
    public javax.swing.JRadioButton rdBtnOpcion2;
    public javax.swing.JRadioButton rdBtnOpcion3;
    public javax.swing.JRadioButton rdBtnOpcion4;
    public javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables

}
