/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Control;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        FondoEleccion = new javax.swing.JPanel();
        lblTituloMain = new javax.swing.JLabel();
        btnAddPreguntas = new javax.swing.JButton();
        btnAbrirEvaluacion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        lblBloom = new javax.swing.JLabel();
        cbBloom = new javax.swing.JComboBox<>();
        lblAsignatura = new javax.swing.JLabel();
        cbAsignatura = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        cbCantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 64)); // NOI18N
        jButton3.setText("<html>Lista de Preguntas</html>");
        jButton3.setToolTipText("");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoEleccion.setBackground(new java.awt.Color(255, 204, 102));

        lblTituloMain.setBackground(java.awt.Color.black);
        lblTituloMain.setFont(new java.awt.Font("Helvetica Neue", 1, 96)); // NOI18N
        lblTituloMain.setForeground(java.awt.Color.white);
        lblTituloMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMain.setText("EVALUADOR");

        btnAddPreguntas.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        btnAddPreguntas.setText("Añadir");
        btnAddPreguntas.setToolTipText("");
        btnAddPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPreguntasActionPerformed(evt);
            }
        });

        btnAbrirEvaluacion.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        btnAbrirEvaluacion.setText("Iniciar");
        btnAbrirEvaluacion.setToolTipText("<html>\nMostrar el listado de todas las preguntas<br>\nguardadas en la base de datos.\n</html>");
        btnAbrirEvaluacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrirEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirEvaluacionActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("<html>\nSalir de la aplicación\n</html>");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cbTipo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Selección Múltiple", "Verdadero o Falso" }));
        cbTipo.setToolTipText("Aquí se elige el tipo de preguntas que vas a añadir al examen.");
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTipo.setText("Tipo de Pregunta");

        lblBloom.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblBloom.setText("Taxonomía de Bloom");

        cbBloom.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cbBloom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "1. Recordar", "2. Comprender", "3. Aplicar", "4. Analizar", "5. Evaluar", "6. Crear" }));
        cbBloom.setToolTipText("Aquí se elige el tipo de preguntas que vas a añadir al examen.");
        cbBloom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloomActionPerformed(evt);
            }
        });

        lblAsignatura.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblAsignatura.setText("Asignatura");

        cbAsignatura.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cbAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "1. Matemáticas", "2. Programación", "3. Bases de Datos", "4. Sistemas Operativos y Redes" }));
        cbAsignatura.setToolTipText("Aquí se elige el tipo de preguntas que vas a añadir al examen.");
        cbAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAsignaturaActionPerformed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblCantidad.setText("Número de Preguntas");

        cbCantidad.setModel(new javax.swing.SpinnerNumberModel());

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enunciado", "Tipo Pregunta", "Nivel Taxonomía", "Tiempo Estimado", "Asignatura"
            }
        ));
        jScrollPane1.setViewportView(tbLista);

        javax.swing.GroupLayout FondoEleccionLayout = new javax.swing.GroupLayout(FondoEleccion);
        FondoEleccion.setLayout(FondoEleccionLayout);
        FondoEleccionLayout.setHorizontalGroup(
            FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoEleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(FondoEleccionLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbBloom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCantidad)
                    .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoEleccionLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnAddPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbrirEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136))
        );
        FondoEleccionLayout.setVerticalGroup(
            FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoEleccionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTituloMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoEleccionLayout.createSequentialGroup()
                        .addComponent(cbAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBloom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBloom, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir)
                        .addComponent(btnAddPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbrirEvaluacion))
                    .addComponent(cbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoEleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoEleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbBloomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloomActionPerformed

    private void cbAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAsignaturaActionPerformed

    private void btnAddPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPreguntasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPreguntasActionPerformed

    private void btnAbrirEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirEvaluacionActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal principal = new Principal();
                Evaluacion evaluacion = new Evaluacion();
                Control control = new Control(evaluacion, principal);
    
                principal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoEleccion;
    public javax.swing.JButton btnAbrirEvaluacion;
    public javax.swing.JButton btnAddPreguntas;
    public javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<String> cbAsignatura;
    public javax.swing.JComboBox<String> cbBloom;
    public javax.swing.JSpinner cbCantidad;
    public javax.swing.JComboBox<String> cbTipo;
    public javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblBloom;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloMain;
    public javax.swing.JTable tbLista;
    // End of variables declaration//GEN-END:variables
}
